### ISSUE TITLE
Radical.analytics example fails with "local variable 'ext' referenced before assignment"

### ISSUE THREAD

**Issue by AymenFJA** [radical-cybertools/radical.analytics#102]
```
Traceback (most recent call last):
  File "test.py", line 24, in <module>
    session = ra.Session(src=src, sid = sid, stype='radical.entk')
  File "/home/aymen/miniconda2/envs/conda_env2/lib/python2.7/site-packages/radical/analytics/session.py", line 38, in __init__
    sid, src, tgt, ext = self._get_sid(sid, src)
  File "/home/aymen/miniconda2/envs/conda_env2/lib/python2.7/site-packages/radical/analytics/session.py", line 205, in _get_sid
    return sid, src, tgt, ext
UnboundLocalError: local variable 'ext' referenced before assignment
```

Radical Stack :
```
  python               : 2.7.15
  pythonpath           : 
  virtualenv           : conda_env1

  radical.analytics    : 0.72.0
  radical.entk         : 0.72.1
  radical.pilot        : 0.72.0
  radical.saga         : 0.72.1
  radical.utils        : 0.72.0
```

**Comment by andre-merzky** [comment]
This should be fixed in devel actually.  Can you give it a try please?  If you confirm this working I'll push out a hotfix.  Thanks!

**Comment by AymenFJA** [comment]
I can confirm that it is working now, with the mentioned radical stack.

Thanks @andre-merzky

**Comment by andre-merzky** [comment]
Hotfix release 0.72.1 is now available on pypi.
