### ISSUE TITLE
ValueError: ['a03n04', '6'] is not in list

### ISSUE THREAD

**Issue by lee212** [radical-cybertools/radical.analytics#107]
```
(analytics) [hrlee@login5.summit radical.analytics]$ radical-stack

  python               : 3.7.3
  pythonpath           : /sw/summit/xalt/1.1.4/site:/sw/summit/xalt/1.1.4/libexec
  virtualenv           : analytics

  radical.analytics    : 0.90.7-v0.72.0-28-ge439909@feature-rp_inspect
  radical.pilot        : 1.0.0
  radical.saga         : 1.0.0
  radical.utils        : 1.0.0

(analytics) [hrlee@login5.summit radical.analytics]$ bin/radical-analytics-inspect 240cpus_100_100_100tasks_1_1_10gens
240cpus_100_100_100tasks_1_1_10gens ....Traceback (most recent call last):
  File "bin/rp_inspect/plot_util.py", line 118, in <module>
    provided, consumed, stats_abs, stats_rel, info = session.utilization(metrics)
  File "/ccs/home/hrlee/.conda/envs/analytics/lib/python3.7/site-packages/radical/analytics/session.py", line 962, in utilization
    consumed  = rp.utils.get_consumed_resources(self)
  File "/ccs/home/hrlee/.conda/envs/analytics/lib/python3.7/site-packages/radical/pilot/utils/prof_utils.py", line 600, in get_consumed_resources
    r0, _ = get_node_index(nodes, node, cpn, gpn)
  File "/ccs/home/hrlee/.conda/envs/analytics/lib/python3.7/site-packages/radical/pilot/utils/prof_utils.py", line 362, in get_node_index
    r0 = node_list.index(node) * (cpn + gpn)
ValueError: ['a03n04', '6'] is not in list
 done
```

**Comment by lee212** [comment]
session data is at https://github.com/radical-experiments/hyperspace_experiments/blob/master/data/raw/nonuniform_tasks/exp4/240cpus_100_100_100tasks_1_1_10gens.tar.gz

**Comment by andre-merzky** [comment]
Thanks for reporting and providing data!  This should be fixed by radical-cybertools/radical.pilot/pull/2029.  Note that the resource utilization plots are still off, they have not been tested for the multi pilot case.  Please open a new ticket if you need that addressed (although I am not sure how quick a fix will be).
