### ISSUE TITLE
matplotlib version 3.0.1+ on python3?

### ISSUE THREAD

**Issue by lee212** [radical-cybertools/radical.analytics#109]
My stack is :
```
(analytics) [hrlee@login1.summit radical.analytics]$ radical-stack

  python               : 3.7.3
  pythonpath           : /sw/summit/xalt/1.1.4/site:/sw/summit/xalt/1.1.4/libexec
  virtualenv           : analytics

  radical.analytics    : 0.90.7-v0.72.0-34-g545607e@devel
  radical.pilot        : 1.0.0-v1.0.0-2-g01c6281@fix-ra_resource_details
  radical.saga         : 1.0.0
  radical.utils        : 1.0.0
```
and my error is generated:
```
(analytics) [hrlee@login1.summit radical.analytics]$ bin/radical-analytics-inspect re.session.login1.hrlee.018274.0000
re.session.login1.hrlee.018274.0000 Traceback (most recent call last):
  File "/autofs/nccs-svm1_home1/hrlee/git/radical.analytics/bin/rp_inspect/plot_state.py", line 13, in <module>
    import matplotlib.pyplot as plt
  File "/ccs/home/hrlee/.conda/envs/analytics/lib/python3.7/site-packages/matplotlib/__init__.py", line 1111, in <module>
    rcParamsOrig = RcParams(rcParams.copy())
  File "/ccs/home/hrlee/.conda/envs/analytics/lib/python3.7/site-packages/matplotlib/__init__.py", line 891, in __getitem__
    from matplotlib import pyplot as plt
  File "/ccs/home/hrlee/.conda/envs/analytics/lib/python3.7/site-packages/matplotlib/pyplot.py", line 32, in <module>
    import matplotlib.colorbar
  File "/ccs/home/hrlee/.conda/envs/analytics/lib/python3.7/site-packages/matplotlib/colorbar.py", line 40, in <module>
    import matplotlib._constrained_layout as constrained_layout
  File "/ccs/home/hrlee/.conda/envs/analytics/lib/python3.7/site-packages/matplotlib/_constrained_layout.py", line 52, in <module>
    from matplotlib.legend import Legend
  File "/ccs/home/hrlee/.conda/envs/analytics/lib/python3.7/site-packages/matplotlib/legend.py", line 43, in <module>
    from matplotlib.offsetbox import HPacker, VPacker, TextArea, DrawingArea
  File "/ccs/home/hrlee/.conda/envs/analytics/lib/python3.7/site-packages/matplotlib/offsetbox.py", line 33, in <module>
    from matplotlib.image import BboxImage
  File "/ccs/home/hrlee/.conda/envs/analytics/lib/python3.7/site-packages/matplotlib/image.py", line 19, in <module>
    from matplotlib.backend_bases import FigureCanvasBase
  File "/ccs/home/hrlee/.conda/envs/analytics/lib/python3.7/site-packages/matplotlib/backend_bases.py", line 46, in <module>
    from matplotlib import (
ImportError: cannot import name 'get_backend' from 'matplotlib' (/ccs/home/hrlee/.conda/envs/analytics/lib/python3.7/site-packages/matplotlib/__init__.py)
```

I upgraded to 3.1.2 according to this: https://github.com/matplotlib/matplotlib/issues/12601

However, ra complains my upgrade:
```
ERROR: radical-analytics 0.90.7 has requirement matplotlib<=3.0, but you'll have matplotlib 3.1.2 which is incompatible.
```

**Comment by mturilli** [comment]
This is now merged into `devel` and will be released in July 2020.
