### ISSUE TITLE
Analytics failed with interactive sessions

### ISSUE THREAD

**Issue by AymenFJA** [radical-cybertools/radical.analytics#186]
```
Traceback (most recent call last):
  File "/ccs/home/aymen/analytics.py", line 9, in <module>
    session = ra.Session(s, 'radical.pilot')
  File "/autofs/nccs-svm1_home1/aymen/ve/rct/lib/python3.7/site-packages/radical/analytics/session.py", line 115, in __init__
    rpu.get_session_description(sid=sid, src=self._src)
  File "/autofs/nccs-svm1_home1/aymen/ve/rct/lib/python3.7/site-packages/radical/pilot/utils/prof_utils.py", line 578, in get_session_description
    reg = ru.read_json('%s/%s.reg.json' % (src, sid))
  File "/autofs/nccs-svm1_home1/aymen/ve/rct/lib/python3.7/site-packages/radical/utils/json_io.py", line 28, in read_json
    with ru_open(fname) as f:
  File "/autofs/nccs-svm1_home1/aymen/ve/rct/lib/python3.7/site-packages/radical/utils/misc.py", line 829, in ru_open
    return open(*args, **kwargs)
FileNotFoundError: [Errno 2] No such file or directory: '/gpfs/alpine/world-shared/gen150/arupcseuva/summit_results/ws/join/rp.session.login3.arupcseuva.019632.0003_client/rp.session.login3.arupcseuva.019632.0003_client.reg.json'
```

**Comment by AymenFJA** [comment]
This issue is no longer happening. Closing.
