### ISSUE TITLE
ValueError: Too many values to unpack

### ISSUE THREAD

**Issue by mingtaiha** [radical-cybertools/radical.analytics#32]
I'm trying to instantiate a `Session` object, but I get the following error:
```
Traceback (most recent call last):
  File "../rad_analytics_test.py", line 18, in <module>
    session = ra.Session(sid, 'radical.pilot', src=src)
  File "/home/mingtha/ve/ve.exec_model_exp_devel/local/lib/python2.7/site-packages/radical/analytics/session.py", line 40, in __init__
    = rp.utils.get_session_profile    (sid=sid, src=self._src)
ValueError: too many values to unpack
```

It seems like there is something up with `radical.utils`.

My `radical-stack`
```
python            : 2.7.6
virtualenv        : /home/mingtha/ve/ve.exec_model_exp_devel
radical.utils     : v0.45-2-g82050c5@devel
saga-python       : split-4-gaa285ca4@devel
radical.pilot     : split-29-g16298d1f@fix-issue_1276
radical.analytics : v0.45@master
```

**Comment by andre-merzky** [comment]
Ming - sorry for the late reply, I forgot to update the ticket :(  Could you please give the RP branch `fix/analytics_utils` a try?  If that does not work, please make a set of profiles + json available.

Thanks!

**Comment by mingtaiha** [comment]
I'm able to create a session and can run some of the `radical.analytics` examples. Thanks

**Comment by andre-merzky** [comment]
Great, thanks for the ping back!
