### ISSUE TITLE
Error when creating a Session object

### ISSUE THREAD

**Issue by mingtaiha** [radical-cybertools/radical.analytics#52]
I'm trying to get information on the timings of my run, like Tx and Tq. However, when I try to parse my runs, I get the following error when I try to create a `Session` object. 

```
sid: rp.session.two.mingtha.017426.0022
row invalid [baseline/512_cu/rp.session.two.mingtha.017426.0022/umgr.scheduling.0.child.prof]: ['1505679200.6181', 'umgr.scheduling.0.child:', '', '', 'sync abs', 'localhost.localdomain:138.201.86.166:1505679200.61:1505679200.61:ntp']
Traceback (most recent call last):
  File "get_unit_tx.py", line 18, in <module>
    session = ra.Session(sid, 'radical.pilot', src=src)
  File "/home/mingtha/ve/ve.exec_model_exp/local/lib/python2.7/site-packages/radical/analytics/session.py", line 40, in __init__
    = rp.utils.get_session_profile    (sid=sid, src=self._src)
  File "/home/mingtha/ve/ve.exec_model_exp/local/lib/python2.7/site-packages/radical/pilot/utils/prof_utils.py", line 86, in get_session_profile
    profiles          = ru.read_profiles(profiles, sid, efilter=efilter)
  File "/home/mingtha/ve/ve.exec_model_exp/local/lib/python2.7/site-packages/radical/utils/profile.py", line 340, in read_profiles
    if pattern in row[field]:
TypeError: argument of type 'NoneType' is not iterable
```

Here's the log files if anyone wants to check that out. [rp.session.two.mingtha.017426.0022.zip](https://github.com/radical-cybertools/radical.analytics/files/1331675/rp.session.two.mingtha.017426.0022.zip)

Here's my `radical-stack`. Do I have to use a different RCT stack in order to parse my logs?
```
  python               : 2.7.12
  pythonpath           : 
  virtualenv           : /home/mingtha/ve/ve.exec_model_exp

  radical.analytics    : v0.45.2-65-g66c0286@rc-v0.46.3
  radical.pilot        : 0.47-v0.46.2-124-g109e344d@rc-v0.46.3
  radical.utils        : 0.47-v0.46-44-gbafa380@rc-v0.46.3
  saga                 : 0.47-v0.46-19-gcfba6e7f@debug-ming
```

**Comment by andre-merzky** [comment]
Thanks Ming - this is fixed now in radical.utils.
