### ISSUE TITLE
import issues 

### ISSUE THREAD

**Issue by jdakka** [radical-cybertools/radical.analytics#55]
```Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/JumanaDakka/environments/venv/lib/python2.7/site-packages/radical/analytics/__init__.py", line 8, in <module>
    from .session import Session
  File "/Users/JumanaDakka/environments/venv/lib/python2.7/site-packages/radical/analytics/session.py", line 481
    parent_uids = self._apply_filter(etype=etype[0])
                                                   ^
IndentationError: unindent does not match any outer indentation level
```

**Comment by mturilli** [comment]
This is blocking for a presentation due at a conference on Friday 17, 2017.

**Comment by andre-merzky** [comment]
Oh!  What version / branch of analytics is that?

**Comment by andre-merzky** [comment]
never mind - found it.

**Comment by andre-merzky** [comment]
A fix has been pushed.

That wrong indentation existed for a year already - but only a recent addition of a check with the right indentation created the Python-parser confusion... :/  Sorry!
